name: CI
on: push

jobs:
  ci:
    name: Type Checking, Linting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # TODO: Update environment variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: expo_example_spring_2024
      PGUSERNAME: expo_example_spring_2024
      PGPASSWORD: expo_example_spring_2024
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER $PGUSERNAME PASSWORD '$PGPASSWORD'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=$PGUSERNAME $PGDATABASE
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm migrate up
      - run: pnpm eslint . --max-warnings 0
      - run: pnpm tsc
